from __future__ import annotations

import re
import sys
import time
from io import BytesIO
from pathlib import Path
from urllib.request import Request, urlopen

from PIL import Image


REPO_ROOT = Path(__file__).resolve().parents[1]
CONSTANTS_PATH = REPO_ROOT / ".vitepress/theme/maplestory/constants.ts"
OUTPUT_DIR = REPO_ROOT / ".vitepress/theme/maplestory/assets/map-banners"
EQUIPMENT_SCENE_DIR = REPO_ROOT / ".vitepress/theme/maplestory/assets/maps"
OUTPUT_SIZE = (896, 256)
MAP_PATTERN = re.compile(r"\['(?P<id>\d+)',\s*'(?P<label>[^']+)'\]")
VERSION_270_MAPS = {
    "150000000",
    "320000000",
    "331000000",
    "402000500",
    "402000600",
    "410004100",
    "875000000",
}
SLOW_MAPS = VERSION_270_MAPS - {"410004100"}
# These maps are intentionally generated by the explicit crop/source manifest
# in generate-curated-map-banners.py.  Do not replace them with the density
# heuristic below: their GMS renders contain only isolated transparent objects.
CURATED_MAP_IDS = {
    "100000000",
    "100030102",
    "100051000",
    "101050000",
    "120000000",
    "130000000",
    "150000000",
    "400000000",
    "402000600",
    "410000200",
    "410004000",
    "410004100",
    "410000402",
    "875010000",
    "402000500",
    "331000000",
}


def read_map_options() -> list[tuple[str, str]]:
    source = CONSTANTS_PATH.read_text(encoding="utf-8")
    options_source = source.split("export const MAP_SCENE_OPTIONS = [", 1)[1].split("] as const", 1)[0]
    return [(match["id"], match["label"]) for match in MAP_PATTERN.finditer(options_source)]


def download_layer(map_id: str, layer: str | None) -> bytes:
    version = "270" if map_id in VERSION_270_MAPS else "248"
    suffix = f"/{layer}" if layer else ""
    url = f"https://maplestory.io/api/GMS/{version}/map/{map_id}/render{suffix}"
    request = Request(url, headers={"User-Agent": "HolyBearTW map banner asset generator"})
    last_error: Exception | None = None
    timeout = 90 if map_id in SLOW_MAPS else 20
    attempts = 1 if map_id in SLOW_MAPS else 2

    for attempt in range(attempts):
        try:
            with urlopen(request, timeout=timeout) as response:
                if response.status != 200:
                    raise RuntimeError(f"HTTP {response.status}")
                return response.read()
        except Exception as error:
            last_error = error
            if attempt < attempts - 1:
                time.sleep(2 ** attempt)

    raise RuntimeError(f"Unable to download map {map_id} layer {layer}: {last_error}")


def download_map(map_id: str) -> tuple[Image.Image, int, list[str]]:
    layers: list[Image.Image] = []
    downloaded_bytes = 0
    errors: list[str] = []

    for layer_name in ("back", None):
        try:
            raw_layer = download_layer(map_id, layer_name)
        except RuntimeError as error:
            errors.append(str(error))
            continue
        downloaded_bytes += len(raw_layer)
        with Image.open(BytesIO(raw_layer)) as layer:
            layers.append(layer.convert("RGBA"))

    if not layers:
        raise RuntimeError("; ".join(errors))

    canvas = Image.new("RGBA", layers[0].size)
    for layer in layers:
        if layer.size != canvas.size:
            raise ValueError(f"Map {map_id} layers use different canvas sizes")
        canvas.alpha_composite(layer)

    return canvas, downloaded_bytes, errors


def densest_window(values: list[int], window_size: int) -> int:
    if window_size >= len(values):
        return 0

    current = sum(values[:window_size])
    best = current
    best_start = 0
    for start in range(1, len(values) - window_size + 1):
        current += values[start + window_size - 1] - values[start - 1]
        if current > best:
            best = current
            best_start = start
    return best_start


def crop_for_banner(source: Image.Image) -> Image.Image:
    alpha_bounds = source.getchannel("A").getbbox()
    if alpha_bounds is None:
        raise ValueError("Map render contains no visible pixels")
    source = source.crop(alpha_bounds)

    target_ratio = OUTPUT_SIZE[0] / OUTPUT_SIZE[1]
    source_ratio = source.width / source.height

    if source_ratio > target_ratio:
        crop_width = round(source.height * target_ratio)
        density = source.getchannel("A").resize((source.width, 1), Image.Resampling.BOX)
        left = densest_window(list(density.tobytes()), crop_width)
        box = (left, 0, left + crop_width, source.height)
    else:
        crop_height = round(source.width / target_ratio)
        density = source.getchannel("A").resize((1, source.height), Image.Resampling.BOX)
        top = densest_window(list(density.tobytes()), crop_height)
        box = (0, top, source.width, top + crop_height)

    return source.crop(box).resize(OUTPUT_SIZE, Image.Resampling.LANCZOS)


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    Image.MAX_IMAGE_PIXELS = None
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    requested_ids = set(sys.argv[1:])
    options = read_map_options()
    if requested_ids:
        options = [(map_id, label) for map_id, label in options if map_id in requested_ids]
        missing_ids = requested_ids - {map_id for map_id, _ in options}
        if missing_ids:
            raise ValueError(f"Unknown map IDs: {', '.join(sorted(missing_ids))}")

    for map_id, label in options:
        if map_id in CURATED_MAP_IDS:
            print(
                f"preserved: {map_id} {label} (curated source; "
                "run generate-curated-map-banners.py to regenerate)",
                flush=True,
            )
            continue
        try:
            source_image, downloaded_bytes, layer_errors = download_map(map_id)
            source_size = source_image.size
            source_description = f"GMS render layers {downloaded_bytes:,} bytes"
            if layer_errors:
                source_description += f" ({'; '.join(layer_errors)})"
            try:
                banner = crop_for_banner(source_image)
            finally:
                source_image.close()
        except (RuntimeError, ValueError) as error:
            # A few valid map records currently have an unavailable endpoint or
            # return a fully transparent render. Use the site's existing,
            # manually approved scene for that exact map ID instead.
            fallback_path = EQUIPMENT_SCENE_DIR / f"{map_id}.webp"
            if not fallback_path.exists():
                raise
            with Image.open(fallback_path) as fallback:
                source_size = fallback.size
                banner = crop_for_banner(fallback.convert("RGBA"))
            source_description = f"approved local scene (GMS unavailable: {error})"

        with banner:
            output_path = OUTPUT_DIR / f"{map_id}.webp"
            banner.save(output_path, "WEBP", quality=84, method=6, exact=True)
            if banner.getchannel("A").getbbox() is None:
                raise ValueError(f"Generated banner {map_id} contains no visible pixels")
            print(
                f"saved: {map_id} {label} "
                f"{source_size[0]}x{source_size[1]} {source_description} -> "
                f"{output_path.stat().st_size:,} bytes",
                flush=True,
            )


if __name__ == "__main__":
    main()
